### ISSUE TITLE
Support dark layout

### ISSUE THREAD

**Issue by jesus2099** [phw/PicardBarcodeScanner#2]
Xiaomi Redmi 7 Android 9.

**Comment by phw** [comment]
I don't know how to test this :(

**Comment by jesus2099** [comment]
![Screenshot_2021-06-10-11-19-29-559_org musicbrainz picard barcodescanner](https://user-images.githubusercontent.com/1401086/121499934-2116d800-c9de-11eb-9db7-76984d643693.jpg)

Now I see it's OK, in day mode.
I keep this open until tonight because maybe the issue was only with night mode.

**Comment by phw** [comment]
Yes, dark mode could be the issue. Never tested this, not something my phone has. I'll check in emulator.

**Comment by phw** [comment]
I updated the title, I think this app needs to be updated in general for dark layouts. Colors are hard coded for light layout.

**Comment by phw** [comment]
Could you do me a favor and check if https://transfer.sh/1hZ3Aps/PicardBarcodeScanner-1.3.apk works for you day and night?

**Comment by jesus2099** [comment]
Sure, with pleasure.
Here is for the record, how it currently looks in night mode:
![Screenshot_2021-06-10-19-33-23-391_com miui gallery](https://user-images.githubusercontent.com/1401086/121571840-cacc8800-ca23-11eb-93ea-63f64c00a659.jpg)

And here is how it looks with your new version. It looks great now:
![Screenshot_2021-06-10-19-39-35-392_org musicbrainz picard barcodescanner](https://user-images.githubusercontent.com/1401086/121571899-df108500-ca23-11eb-859d-952937e86bf4.jpg)
![Screenshot_2021-06-10-19-39-48-081_org musicbrainz picard barcodescanner](https://user-images.githubusercontent.com/1401086/121571906-e2a40c00-ca23-11eb-93c0-323181fefa27.jpg)

**Comment by phw** [comment]
Thanks a lot for testing. I released this now, it should be fine on day mode also.

Probably my last release of this. I'd really like to see this integrated into the MusicBrainz app. Also then loading not only scanned by barcode but also whatever release was searched or browsed via the app. I started looking into this, I think I can submit something for the app team to review. Just need some time :D
