### ISSUE TITLE
Layout problem in "SCAN BARCODE" page and "About" page

### ISSUE THREAD

**Issue by yuhuitech** [phw/PicardBarcodeScanner#20]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, some texts are blocked and some texts overlap with each other. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.5, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply.

**Expected behavior**

I hope that I can see all of the texts after "Please check the...", in this circumstance, they seem to be blocked. 

And in the about page, "version 1.5" overlapped with "Piccard Barcode Scanner". I reckon those two parts should be separated from each other.

**Steps to reproduce the behavior:**

1.use the largest font and display
2.click "SCAN BARCODE"
3.see error

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/128597746-e7f69b05-0025-4c9d-b1cc-566eec154d97.png" alt="Screenshot_16283328841" width="250"/>

**Steps to reproduce the behavior:**

1.use the largest font and display
2.click "About"
3.see error

**Screenshot**

<img src="https://user-images.githubusercontent.com/25502419/128597744-b76e9fbf-41a8-4463-b640-698c6c396c89.png" alt="Screenshot_16283333801" width="250"/>

**Environment**

Version of Piccard Barcode Scanner : 1.5
Device : Google Pixel 2,
OS version : Android 10.0

**Comment by phw** [comment]
@yuhuitech I did a small adjustment for the text positioning in the about view, because the text was moved to the right on smaller font sizes. In my testing this works well with both largest layout / font and smaller settings. Largest:

![grafik](https://user-images.githubusercontent.com/29852/128604115-f25d6bdc-d776-4b9c-a48e-3bfb5daf5935.png)

Normal:

![grafik](https://user-images.githubusercontent.com/29852/128604125-dfbbfc0e-42f0-4180-ad93-1a61d584c282.png)

Thanks again for reporting and submitting a fix. I'm traveling currently, but I will do a new release in 2-3 weeks.

**Comment by yuhuitech** [comment]
@phw This adjustment seems wonderful! I will continue to work on this project, and thanks again for your agreement to my request!

**Comment by phw** [comment]
That's wonderful. I'm also always looking for help translating this little app, see

https://translate.uploadedlobster.com/projects/picard-barcode-scanner/

**Comment by yuhuitech** [comment]
OK, I'll look into it. Thank you!

**Comment by yuhuitech** [comment]
Hi! I have translated this app into Traditional Chinese! Sorry for the late, I am quite busy these days. If you have any questions, please feel free to contact me. :)

**Comment by phw** [comment]
@yuhuitech Did the release with your changes :) Thanks a lot for your help on this, this is great
