### ISSUE TITLE
can´t connect 

### ISSUE THREAD

**Issue by rocky-III** [phw/PicardBarcodeScanner#27]
somehow i can´t connect my phone to my Linux or windows PC. I´m on LineageOS - does this make in difference?

**Comment by phw** [comment]
Hi, even though I have not explicitly tested it, using LineageOS should not make a difference. Not sure if LineageOS offers some possibility that it blocks network access for an app regardless?

Just a few things to check:

- Both your phone and your Windows PC  are on the same network
- You have entered your PCs IP address in the app settings`. Name might also work, but that depends on your local network setup, if in doubt try it with the IP address.
- Picard is running and showing "Listening on port NNNN", where NNNN is a port number like "8000".
- This port number is also configured in the app settings.
- In Picard Options > Advanced > Network the option "Listen only on localhost" is **disabled**
- Your Windows firewall does not block Picard from opening that port

If you have "Listen only on localhost" disabled it and enable it and you have not yet before allowed Picard in the Windows firewall, Windows should show the firewall permission screen where you can allow Picard to communicate over the network.

**Comment by rocky-III** [comment]
@phw THANKS -  FIREWALL   was the keyword which helped...
after i set an entry in the gufw firewall on the PC it works like cream
